name: Update TeX Live Image

on:
  workflow_dispatch:

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull TeX Live image
        run: |
          docker pull chanzz0/texlive
      - name: Run container and update TeX Live packages
        run: |
          CONTAINER_ID=$(docker run -d chanzz0/texlive bash -c "tlmgr update --self --all")
          docker wait $CONTAINER_ID
      - name: Commit updated container as new image
        run: |
          IMAGE_NAME="chanzz0/texlive"
          docker commit $(docker ps -alq) $IMAGE_NAME
      - name: Push updated image to Docker Hub
        run: |
          IMAGE_NAME="chanzz0/texlive"
          docker push $IMAGE_NAME
