name: Podman

on:
  workflow_dispatch:

jobs:
  pull_and_save:
    name: Pull image and save
    runs-on: ubuntu-latest
    permissions:
      # 赋予写入的权限，否则无法发布release
      contents: write
    steps:
      - name: Pull Images
        run: |
          podman pull debian
          podman pull ubuntu
          podman pull archlinux
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
      - name: Push Images
        run: |
          podman push debian
          podman push ubuntu
          podman push archlinux
