name: Test

on:
  workflow_dispatch:
    inputs:
      DOCKER_TAG:
        description: "Please type tag of the docker image"
        required: true
        default: "latest"
  # push:
  #   branches: [main]

jobs:
  build_docker_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    env:
      TL_TEST: "test"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test
        uses: docker/build-push-action@v6
        with:
          context: ./texlive
          platforms: amd64
          push: true
          # tags: "chanzz0/texlive:${{ github.event.inputs.DOCKER_TAG }}"
          tags: "chanzz0/texlive:${{ env.TL_TEST }}"
